server {
  listen 80;
  root /usr/share/nginx/html;
  location /api/ {
    proxy_pass http://backend:3000;
    proxy_set_header Host $host;
  }
  location = /runtime-config.json {
    add_header Cache-Control "no-store";
    add_header Access-Control-Allow-Origin "*";
    try_files $uri =404;
  }
  location = /remoteEntry.js {
    add_header Cache-Control "no-cache";
    add_header Access-Control-Allow-Origin "*";
    try_files $uri =404;
  }
  location / {
    add_header Access-Control-Allow-Origin "*";
    try_files $uri $uri/ =404;
  }
}
